### ISSUE TITLE
how to full back and restore confluence??

### ISSUE THREAD

**Issue by aircjm** [blacklabelops/confluence#13]
how to full back and restore confluence?? My VPS will expires, not ready to renew, how a complete migration to another VPS inside to go ?? thank you very mach

**Comment by blacklabelops** [comment]
Hello,

You need to make a backup of all docker volumes related to confluence. Copy the data to the new machine. Give volumes the same id, restore the data and start the container with the same docker-run-command.

It's all depending on your personal configuration and runtime options. I usually setup both database and confluence in two separate containers. So I have to make backups of confluence volumes and database volumes to archive a proper backup.

~~~~
$ docker volume ls
~~~~

> Shows a list of all the systems volumes

~~~~
$ docker inspect -f '{{ .Mounts }}' your-container-id
~~~~

> Lists the mounts of folder and volumes of your container

~~~~
$ docker volume inspect your-volume-name
~~~~

> Shows the local file systems folder, where the data is saved and can be backed up

A more sophisticated container for making backups and restore files can be found here: [blacklabelops/volumerize](https://github.com/blacklabelops/volumerize)
