### ISSUE TITLE
I use Docker install confluence ,then I want to config emailServer. But I don't find server.xml file??

### ISSUE THREAD

**Issue by aircjm** [blacklabelops/confluence#16]
I use
```shell 
docker run -d --name confluence \
--link postgres:postgres \
-p 80:8090 -p 8091:8091 blacklabelops/confluence
```
install confluence. I very like it because it's very simple to install.

I want to config emailServer, find server.xml isn't in volume/*/_data/ dir . where server.xml ?? I wan't to modify it, thanks

**Comment by blacklabelops** [comment]
Hello aircjm,

How do you configure the email server inside the server.xml? Can you give me an example?

The server.xml is inside the directory `/opt/atlassian/confluence/conf`.

**Comment by aircjm** [comment]
very thanks for feedback.

https://confluence.atlassian.com/doc/setting-up-a-mail-session-for-the-confluence-distribution-6328.html

But I not fand the `server.xml` file in my VPS.

![confluence](https://cloud.githubusercontent.com/assets/18283183/26613554/f0fb5934-45ed-11e7-8c1b-64f785d9555c.png)

thanks

**Comment by blacklabelops** [comment]
The data is written on a docker-volume with the path i mentioned. The data is not written in the named path on your host.

You can either inspect the container and check where docker writes the container volume on your host:

~~~~
$ docker inspect confluence
~~~~

or you can enter the container and change into the directory from inside the container:

~~~~
$ docker exec -it confluence bash
$ cd /opt/atlassian/confluence/conf
~~~~

**Comment by aircjm** [comment]
very thanks. @blacklabelops
