### ISSUE TITLE
Windows fonts in the docker image

### ISSUE THREAD

**Issue by realignedTech** [blacklabelops/confluence#18]
Hi,

it seems like when I start Confluence that Windows and Mac fonts are not installed inside the image:
2017-06-06 11:21:58,793 WARN [Caesium-1-3] [apache.fontbox.util.FontManager] findTTFontname Font not found: Arial-Black

Are the fonts installed according to this KB article?

https://confluence.atlassian.com/confkb/the-text-in-a-powerpoint-excel-or-word-document-looks-different-when-using-the-viewfile-macro-200213562.html

Thanks in advance!

**Comment by Firefishy** [comment]
Package is available in Alphine 3.6: https://pkgs.alpinelinux.org/package/v3.6/community/x86_64/msttcorefonts-installer

**Comment by blacklabelops** [comment]
Okay, will do.

**Comment by blacklabelops** [comment]
Fonts available in blacklabelops/confluence:development. Can anybody test?

**Comment by realignedTech** [comment]
It seems to work, its still missing Tahoma which is not in the msttcorefonts package but I'm not getting log messages for the other fonts anymore
