### ISSUE TITLE
Any way i could help you provide builds for latest 5.5.x 5.6.x 5.7.x and 5.8.x?

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/confluence#19]
We are using your image to test against different confluence versions, down to 5.5.x

Any way we could build 4 new version:

 - 5.5.7
 - 5.6.6
 - 5.7.6
 - 5.8.18

Thos are just the latest patch versions of the minors. AFAICs a PR does not help you, since you just have a history of images, no branches.

I guess the only way this can be done is just changing the Dockerfile https://github.com/blacklabelops/confluence/blob/master/Dockerfile#L4, build and push - but thats just something only you can do, du to the permissions.

How could we solve this?

**Comment by blacklabelops** [comment]
It's time consuming to release and maintain release branches, even if they are the proper solution.

Your always invited to contribute and that can also mean maintaining release branches, help with the build system and implement testing. You only have to fork the repository and start pull requests.

Just changing the version number won't work. The scripts and Dockerfiles are not downward compatible to Confluence version 5. View the commit history you can clearly see the last commit that is version 5 compatible. Branch the commit and then you can simply adjust the version parameter or even build each version with the version as build argument.

**Comment by EugenMayer** [comment]
i see, so what i could do is branch away from the last 5.9 release and create 4 branch PRs 5.5 / 5.6 / 5.7 / 5.8 

i build test them then you can build and publish them - does that sounds like something you would like to go for?

**Comment by blacklabelops** [comment]
It needs a sole 5.x branch which has a build file to build any version you want. I am not using dockerhub build and I will not support dockerhub build. Their error reports are too simple to fix any problem inside a build problem.

**Comment by blacklabelops** [comment]
Example CirlceCI build: https://github.com/blacklabelops/confluence/blob/master/circle.yml

**Comment by EugenMayer** [comment]
So i should prepare a 5.x branch for you, and you do the "version" injections yourself. I do not get how you will benefit from my work if i do not offer you a branch per version to build

**Comment by EugenMayer** [comment]
to be perfectly clear - it is obvious to me how i build images for myself - but thats not the point here. I would like to contribute those to you instead of splitting efforts here

**Comment by blacklabelops** [comment]
Sorry, then it is absolutely unclear for me on what you need. I have a support channel on hipchat where you can state your problem: https://www.hipchat.com/gEorzhvnI

**Comment by blacklabelops** [comment]
Fork the branch `confluence5`, add your versions inside the circleci.yaml file. All versions will be build and pushed to the repository blacklabelops/confluence:versions

Release branch for Confluence 5:
https://github.com/blacklabelops/confluence/tree/confluence5

Build system:
https://circleci.com/gh/blacklabelops/confluence/tree/confluence5
