### ISSUE TITLE
Make ports configurable 

### ISSUE THREAD

**Issue by realignedTech** [blacklabelops/confluence#21]
Hi, when trying to start two instances of Confluence on the same host, you run into the problem of the default port exposed twice which means you have to manually edit both containers in order to get it to work. I would be nice if you could set the confluence standard and synchrony port through ENV exactly like CONFLUENCE_PROXY_PORT so you could start an unlimited number of servers at the same time

**Comment by blacklabelops** [comment]
There is no such problem. You can always remap the port with docker:

~~~~
docker run -d --name confluence1 \
  -p 8090:8090 blacklabelops/confluence
docker run -d --name confluence1 \
  -p 8190:8090 blacklabelops/confluence
~~~~

Also you do not need the synchrony port. Atlassian patched this and synchrony runs by default over a context path.

**Comment by realignedTech** [comment]
Thank you, yes I was asking because of Synchrony. The Confluence docs still refer to 8091 needing to be open in some places. If its not an issue anymore, I think we can forget about this one

Thank you and best regards
