### ISSUE TITLE
Is my confluence Updated ?

### ISSUE THREAD

**Issue by Treenity** [blacklabelops/confluence#41]
Hi, 
thanks for you work, i use you images for my company since 2 month and it's working like a charm !

I have a bug in confluence about inline comments in atatchments that can't be deleted, on atlassian support it's like to be fixed in 6.6.1, but on my confluence footer i see that version is 6.5.0, saw it in system informations too. And my bug is still here, so i think my version is still 6.5.0

Is there a update script i need to launch or maybe a variable i need to set ?
i force pull the :latest image on every update, but it maybe have no effect on already existent volumes ?

i actually use mounts on : 

|/var/atlassian/confluence|
|/opt/atlassian/confluence|

**Comment by Treenity** [comment]
Ok solved problem myself when writed it....i've mounted /opt/atlassian/confluence to persist my settings, but i just saw we can do it with CONFLUENCE_CONFIG_PROPERTY1 const variables...

**Comment by blacklabelops** [comment]
I would advice you to read my upgrade proposal for Jira, it would be the same for Confluence: https://github.com/blacklabelops/jira/issues/64
