### ISSUE TITLE
External PostgreSQL Server

### ISSUE THREAD

**Issue by tomwwinter** [blacklabelops/confluence#45]
Hey, 

i need some help with the database connection.

Im running a plesk installation and run the docker container on a domain. Works fine, but i can't connect to my external PostgreSQL Server. 

If i try to setup the database, i got an error:
```
Can't reach database server or port
SQLState - 08001
org.postgresql.util.PSQLException: The connection attempt failed.
```

Connection to database from my personal PC is no problem and works fine. 

Im not a docker expert, so i need some extra config to support external databases? Open a port or something?

Thank you!

**Comment by blacklabelops** [comment]
This is not Docker related, you do not have to configure anything for outgoing connections.

Your database is simply not reachable from the Jira host. You have to make postgres reachable.

**Comment by tomwwinter** [comment]
Damn. You are right, the problem was not docker related. Problem was the hostname. I used the domain, that works fine in DataGrip but not in confluence. Replaced it by the IP and it works just fine now.
Excuse my fault and thanks for the fast help.

**Comment by tomwwinter** [comment]
Domain resolving fails because of not responsing dns server. 
Added new Variable: `DOCKER_OPTS=-dns 8.8.8.8 -dns 8.8.4.4`

Problem solved.
