### ISSUE TITLE
Proposal: Adjusting Server.xml With Envs

### ISSUE THREAD

**Issue by blacklabelops** [blacklabelops/confluence#9]
You can vote for this feature. Do you need this?

Adjusting the server.xml connector attributes with envs.

Example:

~~~~
$ docker run -d -p 80:8090 -p 8091:8091 \
    --name confluence \
    -e "CONFLUENCE_CONNECTOR_PROPERTY1=proxyPort" \
    -e "CONFLUENCE_CONNECTOR_VALUE1=80" \
    -e "CONFLUENCE_CONNECTOR_PROPERTY2=proxyName" \
    -e "CONFLUENCE_CONNECTOR_VALUE2=confluence.example.org" \
    blacklabelops/confluence
~~~~

**Comment by luzlab** [comment]
Definitely - it would be great to be able to provide the same environment variables as the Jira container... so `CONFLUENCE_DATABASE_URL` and `CONFLUENCE_DB_PASSWORD`.

**Comment by blacklabelops** [comment]
Ditching this feature. No additional gain.
